development:
  adapter: postgresql
  database: gmon
  username: postgres
  password: moc1998
  host: localhost

production:
  adapter: postgresql
  database: gmon
  username: postgres
  password: moc1998
  host: 10.193.198.96

homologacao:
  adapter: postgresql
  database: gmon
  username: postgres
  password: moc1998
  host: localhost