development:
  adapter: postgresql
  database: gmon
  username: postgres
  password: moc1998
  host: localhost

production:
  adapter: postgresql
  database: gmon
  username: postgres
  password: moc1998
  host: localhost

homologacao:
  adapter: postgresql
  database: gmon
  username: postgres
  password: moc1998
  host: localhost